# Panda

### Getting and knowing the data
1. Know the data before starting the program
2. Name the dataset or varaibles relevant to the provided data

### How to import panda

In [2]:
import pandas as pd

### How to read a tsv file Data.tsv.txt which is placed in the same file path?

### pd.read_csv(filepath_or_buffer="Data.tsv.txt") ?
does this code read tsv file?

In [6]:
pd.read_csv(filepath_or_buffer="Data.tsv.txt") #gives error as data.tsv is tab seperated values parser error

ParserError: Error tokenizing data. C error: Expected 1 fields in line 6, saw 5

### pd.read_csv(filepath_or_buffer="Data.tsv.txt") ?
if this code doesnt read what will read?

In [3]:
import pandas as pd
order_details=pd.read_csv(filepath_or_buffer="Data.tsv.txt",sep="\t") #delimiter was given as tab (escape sequencing code"

In [4]:
order_details

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98
...,...,...,...,...,...
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",$11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",$11.75
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$11.25
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",$8.75
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$8.75

### pd.read_table(filepath_or_buffer="insurance.csv")? does this show correct data if not what needs to be used?

In [8]:
pd.read_table(filepath_or_buffer="insurance.csv") #as it is csv it wont come in proper manner you need to use proper delimiter

      age,sex,bmi,children,smoker,region,charges
0       19,female,27.9,0,yes,southwest,16884.924
1         18,male,33.77,1,no,southeast,1725.5523
2             28,male,33,3,no,southeast,4449.462
3      33,male,22.705,0,no,northwest,21984.47061
4         32,male,28.88,0,no,northwest,3866.8552
...                                          ...
1333     50,male,30.97,3,no,northwest,10600.5483
1334    18,female,31.92,0,no,northeast,2205.9808
1335    18,female,36.85,0,no,southeast,1629.8335
1336      21,female,25.8,0,no,southwest,2007.945
1337  61,female,29.07,0,yes,northwest,29141.3603

[1338 rows x 1 columns]

In [9]:
pd.read_table(filepath_or_buffer="insurance.csv",sep=",")

      age     sex     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
1333   50    male  30.970         3     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

[1338 rows x 7 columns]

### What are function and atributes

In [ ]:
Functions - () has parenthesis
Attributes - Doesnt have parenthesis-  it is mentioned as instances

### What are rows and columns called in pandas?

In [ ]:
Terminology for rows and columns
1. Rows = Observations/records
2. Columns - Features/Parameters

### 1.1 Perform initial analysis of data

### How to find the shape of the data frame order_details dataframe? What does it give?

In [14]:
order_details.shape #shape is an attribute

(4622, 5)

### How to find whether there is null entry in order_details dataframe?

In [15]:
order_details.isnull() #gives nullentry for each record

      order_id  quantity  item_name  choice_description  item_price
0        False     False      False                True       False
1        False     False      False               False       False
2        False     False      False               False       False
3        False     False      False                True       False
4        False     False      False               False       False
...        ...       ...        ...                 ...         ...
4617     False     False      False               False       False
4618     False     False      False               False       False
4619     False     False      False               False       False
4620     False     False      False               False       False
4621     False     False      False               False       False

[4622 rows x 5 columns]

### How to find total sum of null entry in order_details dataframe? What extra function do we have to use?

In [16]:
order_details.isnull().sum() # total nulls in each column if you use more than two functions continously its known as chain of functions

order_id                 0
quantity                 0
item_name                0
choice_description    1246
item_price               0
dtype: int64

### How to find the descpritive statistics of a dataframe? what type of datatype does it include in it?

In [17]:
order_details.describe() # gives descriptive statistics describe attribute is different describe() function is different

          order_id     quantity
count  4622.000000  4622.000000
mean    927.254868     1.075725
std     528.890796     0.410186
min       1.000000     1.000000
25%     477.250000     1.000000
50%     926.000000     1.000000
75%    1393.000000     1.000000
max    1834.000000    15.000000

### How to find the datatypes of a dataframe? is datatype a function?

In [18]:
order_details.dtypes #gives datatypes of the dataframe, dtype is a attribute without paranthesis, it is also called as instances

order_id               int64
quantity               int64
item_name             object
choice_description    object
item_price            object
dtype: object

import pandas as pd
order_details=pd.read_csv(filepath_or_buffer="Data.tsv.txt",sep="\t")
order_details
order_details.isnull()
order_details.isnull().sum()
order_details.describe()

### How to find the descriptive statiscs of all the COLUMNS?

In [20]:
order_details.describe(include="all")

           order_id     quantity     item_name choice_description item_price
count   4622.000000  4622.000000          4622               3376       4622
unique          NaN          NaN            50               1043         78
top             NaN          NaN  Chicken Bowl        [Diet Coke]     $8.75
freq            NaN          NaN           726                134        730
mean     927.254868     1.075725           NaN                NaN        NaN
std      528.890796     0.410186           NaN                NaN        NaN
min        1.000000     1.000000           NaN                NaN        NaN
25%      477.250000     1.000000           NaN                NaN        NaN
50%      926.000000     1.000000           NaN                NaN        NaN
75%     1393.000000     1.000000           NaN                NaN        NaN
max     1834.000000    15.000000           NaN                NaN        NaN

### What statisctis are displayed for the object type column and not for numerical columns?

Top
Unique
Frequency
This will be populated inly for object type

### Final recall of the all coding snippet used in this section?

order_details.shape #shape is an attribute
order_details.dtypes #gives datatypes of the , dtype is a attribute without bracket also called as instances
order_details.isnull() #gives nullentry for each record
order_details.isnull().sum() # total nulls in each column if you use more than two functions continously its known as chain of functions
order_details.describe() # gives descriptive statistics for numeric columns
order_details.describe(include="all") # gives descriptive statistics for numeric and objective

### 1.2 Find out the items sold out in the restaraunt

### Which function gives unique values for all the features?

In [21]:
order_details.nunique() #gives unique values for all the features

order_id              1834
quantity                 9
item_name               50
choice_description    1043
item_price              78
dtype: int64

### Which CODE displays all the records for a particular column or feature?

In [22]:
order_details["item_name"] #gives all the records for the feature item_name

0                Chips and Fresh Tomato Salsa
1                                        Izze
2                            Nantucket Nectar
3       Chips and Tomatillo-Green Chili Salsa
4                                Chicken Bowl
                        ...
4617                            Steak Burrito
4618                            Steak Burrito
4619                       Chicken Salad Bowl
4620                       Chicken Salad Bowl
4621                       Chicken Salad Bowl
Name: item_name, Length: 4622, dtype: object

### Which functions shows unique records available in  the feature/column named item_name?

In [23]:
order_details["item_name"].unique() #gives unique records for the feature item_name

array(['Chips and Fresh Tomato Salsa', 'Izze', 'Nantucket Nectar',
       'Chips and Tomatillo-Green Chili Salsa', 'Chicken Bowl',
       'Side of Chips', 'Steak Burrito', 'Steak Soft Tacos',
       'Chips and Guacamole', 'Chicken Crispy Tacos',
       'Chicken Soft Tacos', 'Chicken Burrito', 'Canned Soda',
       'Barbacoa Burrito', 'Carnitas Burrito', 'Carnitas Bowl',
       'Bottled Water', 'Chips and Tomatillo Green Chili Salsa',
       'Barbacoa Bowl', 'Chips', 'Chicken Salad Bowl', 'Steak Bowl',
       'Barbacoa Soft Tacos', 'Veggie Burrito', 'Veggie Bowl',
       'Steak Crispy Tacos', 'Chips and Tomatillo Red Chili Salsa',
       'Barbacoa Crispy Tacos', 'Veggie Salad Bowl',
       'Chips and Roasted Chili-Corn Salsa',
       'Chips and Roasted Chili Corn Salsa', 'Carnitas Soft Tacos',
       'Chicken Salad', 'Canned Soft Drink', 'Steak Salad Bowl',
       '6 Pack Soft Drink', 'Chips and Tomatillo-Red Chili Salsa', 'Bowl',
       'Burrito', 'Crispy Tacos', 'Carnitas Crispy Tacos', 'Steak Salad',
       'Chips and Mild Fresh Tomato Salsa', 'Veggie Soft Tacos',
       'Carnitas Salad Bowl', 'Barbacoa Salad Bowl', 'Salad',
       'Veggie Crispy Tacos', 'Veggie Salad', 'Carnitas Salad'],
      dtype=object)

### Which prints the unique values of te column item name ?

In [24]:
print(order_details["item_name"].unique())

['Chips and Fresh Tomato Salsa' 'Izze' 'Nantucket Nectar'
 'Chips and Tomatillo-Green Chili Salsa' 'Chicken Bowl' 'Side of Chips'
 'Steak Burrito' 'Steak Soft Tacos' 'Chips and Guacamole'
 'Chicken Crispy Tacos' 'Chicken Soft Tacos' 'Chicken Burrito'
 'Canned Soda' 'Barbacoa Burrito' 'Carnitas Burrito' 'Carnitas Bowl'
 'Bottled Water' 'Chips and Tomatillo Green Chili Salsa' 'Barbacoa Bowl'
 'Chips' 'Chicken Salad Bowl' 'Steak Bowl' 'Barbacoa Soft Tacos'
 'Veggie Burrito' 'Veggie Bowl' 'Steak Crispy Tacos'
 'Chips and Tomatillo Red Chili Salsa' 'Barbacoa Crispy Tacos'
 'Veggie Salad Bowl' 'Chips and Roasted Chili-Corn Salsa'
 'Chips and Roasted Chili Corn Salsa' 'Carnitas Soft Tacos'
 'Chicken Salad' 'Canned Soft Drink' 'Steak Salad Bowl'
 '6 Pack Soft Drink' 'Chips and Tomatillo-Red Chili Salsa' 'Bowl'
 'Burrito' 'Crispy Tacos' 'Carnitas Crispy Tacos' 'Steak Salad'
 'Chips and Mild Fresh Tomato Salsa' 'Veggie Soft Tacos'
 'Carnitas Salad Bowl' 'Barbacoa Salad Bowl' 'Salad' 'Veggie Crispy Tacos'
 'Veggie Salad' 'Carnitas Salad']

### Give me the list of top 5 selling items BASED On the quantity sold?

### Group the column itemname?? Does it give output?

In [76]:
order_details.groupby(by="item_name")

### Group the column itemname? selects the coulumn quantity ? Does it give output?

In [ ]:
order_details.groupby(by="item_name")["quantity"]

### Group the column itemname? selects the coulumn quantity ? perform sum function for quantity?

In [5]:
order_details.groupby(by="item_name")["quantity"].sum()

item_name
6 Pack Soft Drink                         55
Barbacoa Bowl                             66
Barbacoa Burrito                          91
Barbacoa Crispy Tacos                     12
Barbacoa Salad Bowl                       10
Barbacoa Soft Tacos                       25
Bottled Water                            211
Bowl                                       4
Burrito                                    6
Canned Soda                              126
Canned Soft Drink                        351
Carnitas Bowl                             71
Carnitas Burrito                          60
Carnitas Crispy Tacos                      8
Carnitas Salad                             1
Carnitas Salad Bowl                        6
Carnitas Soft Tacos                       40
Chicken Bowl                             761
Chicken Burrito                          591
Chicken Crispy Tacos                      50
Chicken Salad                              9
Chicken Salad Bowl                       123
Chicken Soft Tacos                       120
Chips                                    230
Chips and Fresh Tomato Salsa             130
Chips and Guacamole                      506
Chips and Mild Fresh Tomato Salsa          1
Chips and Roasted Chili Corn Salsa        23
Chips and Roasted Chili-Corn Salsa        18
Chips and Tomatillo Green Chili Salsa     45
Chips and Tomatillo Red Chili Salsa       50
Chips and Tomatillo-Green Chili Salsa     33
Chips and Tomatillo-Red Chili Salsa       25
Crispy Tacos                               2
Izze                                      20
Nantucket Nectar                          29
Salad                                      2
Side of Chips                            110
Steak Bowl                               221
Steak Burrito                            386
Steak Crispy Tacos                        36
Steak Salad                                4
Steak Salad Bowl                          31
Steak Soft Tacos                          56
Veggie Bowl                               87
Veggie Burrito                            97
Veggie Crispy Tacos                        1
Veggie Salad                               6
Veggie Salad Bowl                         18
Veggie Soft Tacos                          8
Name: quantity, dtype: int64

### Group the column itemname? selects the coulumn quantity ? perform sum function for quantity? Sort the value in ascending?

In [49]:
order_details.groupby(by="item_name")["quantity"].sum().sort_values(ascending=False).head()

item_name
Chicken Bowl           761
Chicken Burrito        591
Chips and Guacamole    506
Steak Burrito          386
Canned Soft Drink      351
Name: quantity, dtype: int64

### Give me the list of least 5 selling items

In [53]:
order_details.groupby(by="item_name")["quantity"].sum().sort_values().head()

item_name
Carnitas Salad                       1
Chips and Mild Fresh Tomato Salsa    1
Veggie Crispy Tacos                  1
Crispy Tacos                         2
Salad                                2
Name: quantity, dtype: int64

### Give me the codes used in the above chapter 1.1 top selling?

In [ ]:
order_details.groupby(by="item_name) #groups item_name
order_details.groupby(by="item_name).["quantity"] #selects the coulomn to perform a function
order_details.groupby(by="item_name).["quantity"].sum() #sum function is performed for quantity
order_details.groupby(by="item_name).["quantity"].sum().sort_values() #sorts value in ascending order
order_details.groupby(by="item_name).["quantity"].sum().sort_values(ascending=False) # sorts the value in descending order
order_details.groupby(by="item_name).["quantity"].sum().sort_values(ascending=False).head() # prints first 5 item_name with highest sold quantities
order_details.groupby(by="item_name).["quantity"].sum().sort_values(ascending=False).head(10)#first 10

### Chapter 2 : Data cleaning

### Need to remove dollar in item_name to make it float? does the below code work?
order_details["item_price"].replace(to_replace="$",value=" ")

In [168]:
order_details=pd.read_csv("Data.tsv.txt",sep="\t")

In [174]:
order_details["item_price"].replace(to_replace="$",value="") # this one wont work

0        $2.39
1        $3.39
2        $3.39
3        $2.39
4       $16.98
         ...
4617    $11.75
4618    $11.75
4619    $11.25
4620     $8.75
4621     $8.75
Name: item_price, Length: 4622, dtype: object

In [173]:
order_details["item_price"].replace(to_replace="\$",value="", regex=True)

0        2.39
1        3.39
2        3.39
3        2.39
4       16.98
         ...
4617    11.75
4618    11.75
4619    11.25
4620     8.75
4621     8.75
Name: item_price, Length: 4622, dtype: object

### What function used to remove the dollar from the item_price?

In [20]:
k=pd.Series(data=["a",2,3])
q=k.astype("str")
type(q)
q.str.replace("a","b")

0    b
1    2
2    3
dtype: object

In [65]:
k="$23.6"
k.replace("$","")
str.replace("$","")

'23.6'

In [87]:
order_details["item_price"].str.replace("$","") #removes dollar sign but keeps the dtype as object but we need in float

0        2.39
1        3.39
2        3.39
3        2.39
4       16.98
         ...
4617    11.75
4618    11.75
4619    11.25
4620     8.75
4621     8.75
Name: item_price, Length: 4622, dtype: object

### Need to change the datatype object to float can i use the below code to change?
float(order_details["item_price"].str.replace("$",""))\

In [67]:
float(order_details["item_price"].str.replace("$","")) #gives series error

TypeError: cannot convert the series to <class 'float'>

### What to use to change the datatype object to float ?

In [89]:
order_details["item_price"].str.replace("$","").astype(float) # this is the right coding to remove and convert the object to float

0        2.39
1        3.39
2        3.39
3        2.39
4       16.98
        ...
4617    11.75
4618    11.75
4619    11.25
4620     8.75
4621     8.75
Name: item_price, Length: 4622, dtype: float64

### Will it change the data type of the column in the order_details data frame in to float in the orginal data? what needs to be done?

In [90]:
order_details

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98
...,...,...,...,...,...
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",$11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",$11.75
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$11.25
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",$8.75
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$8.75

In [70]:
order_details.dtypes #still the iten_price is an object

order_id               int64
quantity               int64
item_name             object
choice_description    object
item_price            object
dtype: object

### What to code to change the orginal data?

In [132]:
order_details["item_price"]=order_details["item_price"].str.replace("$","").astype(float) # converts the column and saves it in the column

In [133]:
order_details.dtypes

order_id                int64
quantity                int64
item_name              object
choice_description     object
item_price            float64
dtype: object

### Can we convert a series to string is it possible to replace the value? 
k=pd.Series(data=["a",2,3])
will k.string.replace("a","b")

In [175]:
k=pd.Series(data=["a",2,3])
q=k.astype("str")
type(q)
q.str.replace("a","b")

0    b
1    2
2    3
dtype: object

### Task given my Proitbridge
1. Find out top 5 selling items individual revenue it made
2. Total revenue of the top 5 item sold
3. Find atleast two more questions on the same dataset?

### What does the new dataframe describe? whats the difference? And what can we do?

In [74]:
order_details.describe() #now we get a new descriptive statistics for the item_price based on this we can ask further data analysis questions

          order_id     quantity   item_price
count  4622.000000  4622.000000  4622.000000
mean    927.254868     1.075725     7.464336
std     528.890796     0.410186     4.245557
min       1.000000     1.000000     1.090000
25%     477.250000     1.000000     3.390000
50%     926.000000     1.000000     8.750000
75%    1393.000000     1.000000     9.250000
max    1834.000000    15.000000    44.250000

### Can you get me which item had more revenue?

In [96]:
order_details

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,2.39
1,1,1,Izze,[Clementine],3.39
2,1,1,Nantucket Nectar,[Apple],3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",16.98
...,...,...,...,...,...
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",11.75
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",11.25
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",8.75
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",8.75

In [120]:
order_details.groupby(by="item_name")[["item_price"]].sum().sort_values(ascending=False,by="item_price").head(10)

                     item_price
item_name
Chicken Bowl            7342.73
Chicken Burrito         5575.82
Steak Burrito           3851.43
Steak Bowl              2260.19
Chips and Guacamole     2201.04
Chicken Salad Bowl      1228.75
Chicken Soft Tacos      1108.09
Veggie Burrito           934.77
Barbacoa Burrito         894.75
Veggie Bowl              867.99

### Can you get me which items had more revenue and with their quantities? please sort it in accord to the price?

In [ ]:
##use double square brackets to use more than one column and as two columns are there in sort values u need to give by value

In [107]:
order_details.groupby(by="item_name")[["quantity","item_price"]].sum().sort_values(ascending=False,by="item_price")

                                       quantity  item_price
item_name
Chicken Bowl                                761     7342.73
Chicken Burrito                             591     5575.82
Steak Burrito                               386     3851.43
Steak Bowl                                  221     2260.19
Chips and Guacamole                         506     2201.04
Chicken Salad Bowl                          123     1228.75
Chicken Soft Tacos                          120     1108.09
Veggie Burrito                               97      934.77
Barbacoa Burrito                             91      894.75
Veggie Bowl                                  87      867.99
Carnitas Bowl                                71      736.71
Barbacoa Bowl                                66      672.36
Carnitas Burrito                             60      597.83
Steak Soft Tacos                             56      536.05
Chips                                       230      494.34
Chicken Crispy Tacos                         50      472.13
Canned Soft Drink                           351      438.75
Carnitas Soft Tacos                          40      375.94
Chips and Fresh Tomato Salsa                130      361.36
Steak Crispy Tacos                           36      357.34
6 Pack Soft Drink                            55      356.95
Steak Salad Bowl                             31      343.59
Bottled Water                               211      302.56
Barbacoa Soft Tacos                          25      250.46
Side of Chips                               110      185.90
Veggie Salad Bowl                            18      182.50
Chips and Tomatillo Red Chili Salsa          50      147.50
Canned Soda                                 126      137.34
Chips and Tomatillo Green Chili Salsa        45      132.75
Barbacoa Crispy Tacos                        12      120.21
Barbacoa Salad Bowl                          10      106.40
Nantucket Nectar                             29       98.31
Chicken Salad                                 9       81.09
Chips and Tomatillo-Green Chili Salsa        33       78.87
Carnitas Crispy Tacos                         8       77.96
Veggie Soft Tacos                             8       73.96
Chips and Roasted Chili Corn Salsa           23       67.85
Izze                                         20       67.80
Carnitas Salad Bowl                           6       66.34
Chips and Tomatillo-Red Chili Salsa          25       59.75
Veggie Salad                                  6       50.94
Burrito                                       6       44.40
Chips and Roasted Chili-Corn Salsa           18       43.02
Steak Salad                                   4       35.66
Bowl                                          4       29.60
Salad                                         2       14.80
Crispy Tacos                                  2       14.80
Carnitas Salad                                1        8.99
Veggie Crispy Tacos                           1        8.49
Chips and Mild Fresh Tomato Salsa             1        3.00

### 1. Find out top 5 selling items individual revenue it made with group by and without group by?

In [114]:
order_details.groupby(by="item_name")["item_price"].max().sort_values(ascending=False) # here max is very important as your grouping some aggregation is needed to display

item_name
Chips and Fresh Tomato Salsa             44.25
Carnitas Bowl                            35.25
Chicken Burrito                          35.00
Veggie Burrito                           33.75
Chicken Bowl                             32.94
Steak Burrito                            27.75
Steak Bowl                               26.07
Steak Salad Bowl                         23.78
Chicken Salad Bowl                       22.50
Bowl                                     22.20
Chicken Soft Tacos                       21.96
Barbacoa Crispy Tacos                    18.50
Carnitas Burrito                         18.50
Steak Soft Tacos                         18.50
Steak Crispy Tacos                       17.98
Carnitas Crispy Tacos                    17.98
Chips and Guacamole                      17.80
Chicken Crispy Tacos                     17.50
Veggie Soft Tacos                        16.98
Veggie Bowl                              16.98
Bottled Water                            15.00
Side of Chips                            13.52
6 Pack Soft Drink                        12.98
Carnitas Salad Bowl                      11.89
Barbacoa Salad Bowl                      11.89
Barbacoa Bowl                            11.75
Barbacoa Soft Tacos                      11.75
Barbacoa Burrito                         11.75
Carnitas Soft Tacos                      11.75
Veggie Salad Bowl                        11.25
Chicken Salad                            10.98
Steak Salad                               8.99
Carnitas Salad                            8.99
Veggie Crispy Tacos                       8.49
Veggie Salad                              8.49
Crispy Tacos                              7.40
Burrito                                   7.40
Salad                                     7.40
Chips and Tomatillo-Red Chili Salsa       7.17
Nantucket Nectar                          6.78
Chips                                     6.45
Chips and Roasted Chili Corn Salsa        5.90
Chips and Tomatillo Green Chili Salsa     5.90
Chips and Tomatillo Red Chili Salsa       5.90
Canned Soft Drink                         5.00
Chips and Tomatillo-Green Chili Salsa     4.78
Canned Soda                               4.36
Izze                                      3.39
Chips and Mild Fresh Tomato Salsa         3.00
Chips and Roasted Chili-Corn Salsa        2.39
Name: item_price, dtype: float64

In [26]:
order_details[["item_name","item_price"]].sort_values(ascending=False, by="item_price")#without grouping by

                item_name item_price
2624     Steak Salad Bowl     $9.39
4419     Steak Salad Bowl     $9.39
4036     Steak Salad Bowl     $9.39
1825  Barbacoa Salad Bowl     $9.39
3115  Carnitas Salad Bowl     $9.39
...                   ...        ...
3145          Canned Soda     $1.09
414           Canned Soda     $1.09
3162          Canned Soda     $1.09
821           Canned Soda     $1.09
1457          Canned Soda     $1.09

[4622 rows x 2 columns]

### What is very important here to get output is the below code correct?
order_details.groupby(by="item_name")[["item_price"]].sort_values(ascending=False)

In [115]:
order_details.groupby(by="item_name")[["item_price"]].sort_values(ascending=False)

AttributeError: 'DataFrameGroupBy' object has no attribute 'sort_values'

In [116]:
order_details.groupby(by="item_name")[["item_price"]].max().sort_values(ascending=False) #need to include max as its grouped atleast one of the aggregate function is needed

TypeError: DataFrame.sort_values() missing 1 required positional argument: 'by'

In [117]:
order_details.groupby(by="item_name")["item_price"].max().sort_values(ascending=False) # need to remove extra square bracket

item_name
Chips and Fresh Tomato Salsa             44.25
Carnitas Bowl                            35.25
Chicken Burrito                          35.00
Veggie Burrito                           33.75
Chicken Bowl                             32.94
Steak Burrito                            27.75
Steak Bowl                               26.07
Steak Salad Bowl                         23.78
Chicken Salad Bowl                       22.50
Bowl                                     22.20
Chicken Soft Tacos                       21.96
Barbacoa Crispy Tacos                    18.50
Carnitas Burrito                         18.50
Steak Soft Tacos                         18.50
Steak Crispy Tacos                       17.98
Carnitas Crispy Tacos                    17.98
Chips and Guacamole                      17.80
Chicken Crispy Tacos                     17.50
Veggie Soft Tacos                        16.98
Veggie Bowl                              16.98
Bottled Water                            15.00
Side of Chips                            13.52
6 Pack Soft Drink                        12.98
Carnitas Salad Bowl                      11.89
Barbacoa Salad Bowl                      11.89
Barbacoa Bowl                            11.75
Barbacoa Soft Tacos                      11.75
Barbacoa Burrito                         11.75
Carnitas Soft Tacos                      11.75
Veggie Salad Bowl                        11.25
Chicken Salad                            10.98
Steak Salad                               8.99
Carnitas Salad                            8.99
Veggie Crispy Tacos                       8.49
Veggie Salad                              8.49
Crispy Tacos                              7.40
Burrito                                   7.40
Salad                                     7.40
Chips and Tomatillo-Red Chili Salsa       7.17
Nantucket Nectar                          6.78
Chips                                     6.45
Chips and Roasted Chili Corn Salsa        5.90
Chips and Tomatillo Green Chili Salsa     5.90
Chips and Tomatillo Red Chili Salsa       5.90
Canned Soft Drink                         5.00
Chips and Tomatillo-Green Chili Salsa     4.78
Canned Soda                               4.36
Izze                                      3.39
Chips and Mild Fresh Tomato Salsa         3.00
Chips and Roasted Chili-Corn Salsa        2.39
Name: item_price, dtype: float64

### Least sold 5 items individualy sold?

In [122]:
order_details.groupby(by="item_name")["item_price"].min().sort_values().head()

item_name
Bottled Water        1.09
Canned Soda          1.09
Canned Soft Drink    1.25
Side of Chips        1.69
Chips                1.99
Name: item_price, dtype: float64

### Least sold 5 items sold overall?

In [123]:
order_details.groupby(by="item_name")["item_price"].sum().sort_values().head()

item_name
Chips and Mild Fresh Tomato Salsa     3.00
Veggie Crispy Tacos                   8.49
Carnitas Salad                        8.99
Crispy Tacos                         14.80
Salad                                14.80
Name: item_price, dtype: float64

### Least sold 5 items overall with their price and quantity? Sorted by price value?

In [126]:
order_details.groupby(by="item_name")[["item_price","quantity"]].sum().sort_values(by="item_price").head()

                                   item_price  quantity
item_name
Chips and Mild Fresh Tomato Salsa        3.00         1
Veggie Crispy Tacos                      8.49         1
Carnitas Salad                           8.99         1
Crispy Tacos                            14.80         2
Salad                                   14.80         2

### Least sold 5 items overall with their price and quantity? Sorted by quantity value?

In [127]:
order_details.groupby(by="item_name")[["item_price","quantity"]].sum().sort_values(by="quantity").head()

                                   item_price  quantity
item_name
Carnitas Salad                           8.99         1
Chips and Mild Fresh Tomato Salsa        3.00         1
Veggie Crispy Tacos                      8.49         1
Crispy Tacos                            14.80         2
Salad                                   14.80         2

### I need maximum how much quantity did someone ordered "Chicken Bowl"?

In [137]:
order_details[order_details["item_name"]=="Chicken Bowl"].max()

order_id                                                           1828
quantity                                                              3
item_name                                                  Chicken Bowl
choice_description    [[Tomatillo-Red Chili Salsa (Hot), Tomatillo-G...
item_price                                                        32.94
dtype: object

### Chapter 3 - Panda data structures

### 1D and 2D data structure of panda called as?

In [ ]:
. 1D - Series
· 2D - DataFrame

### How to call a series in pandas? What function is used and argument?
pd.series(data=1) is this right

In [138]:
pd.series(data=1) #series should be Series

AttributeError: module 'pandas' has no attribute 'series'

In [139]:
pd.Series(data=1)

0    1
dtype: int64

### How to put list of numbers in this and what will be the datatype if we put list of numbers and string? is the below code correct?
pd.Series(data=1,2,3)

In [140]:
pd.Series(data=1,2,3)

SyntaxError: positional argument follows keyword argument (3306290847.py, line 1)

In [141]:
pd.Series(data=[1,2,3])

0    1
1    2
2    3
dtype: int64

In [142]:
pd.Series(data=[1,2,3.5])

0    1.0
1    2.0
2    3.5
dtype: float64

In [143]:
pd.Series(data=[1,2,"ravi"])

0       1
1       2
2    ravi
dtype: object

### How to get dataframes for the value 1,2,"Ravi"? will i ttake?

In [146]:
pd.DataFrame(data=[1,2,"ravi"])

      0
0     1
1     2
2  ravi

### is the below code correct?
pd.dataframe(data=[1,2,"ravi"])

In [147]:
pd.dataframe(data=[1,2,"ravi"]) #no it should be titled

AttributeError: module 'pandas' has no attribute 'dataframe'

In [148]:
pd.DataFrame(data=[1,2,"ravi"])

      0
0     1
1     2
2  ravi

### Will this below dictionary work in series or dataframe?

pd.Series(data={'Ravi': [20, 30, 40],
 'Shiva': [20, 30, 40],
 'Kamat': [20, 30, 40],
 'Udupi': [20, 30, 40]})

In [ ]:
#it works in both series and dataframe

In [150]:
pd.Series(data={'Ravi': [20, 30, 40],
 'Shiva': [20, 30, 40],
 'Kamat': [20, 30, 40],
 'Udupi': [20, 30, 40]})

Ravi     [20, 30, 40]
Shiva    [20, 30, 40]
Kamat    [20, 30, 40]
Udupi    [20, 30, 40]
dtype: object

In [151]:
pd.DataFrame(data={'Ravi': [20, 30, 40],
 'Shiva': [20, 30, 40],
 'Kamat': [20, 30, 40],
 'Udupi': [20, 30, 40]})

   Ravi  Shiva  Kamat  Udupi
0    20     20     20     20
1    30     30     30     30
2    40     40     40     40

### Why cant we convert the below code to float and throwed value that the series doesnt have attribute float?

order_details["item_price"].str.replace("$","").float()

In [154]:
order_details["item_price"].str.replace("$","").float()

AttributeError: 'Series' object has no attribute 'float'

In [ ]:
# Series' object has no attribute 'float' this means there is no function or instance like float() to convert the series

In [ ]:
# the below give series but this to convert we need to find right attribute to use

In [155]:
order_details["item_price"].str.replace("$","")

0        2.39
1        3.39
2        3.39
3        2.39
4       16.98
         ...
4617    11.75
4618    11.75
4619    11.25
4620     8.75
4621     8.75
Name: item_price, Length: 4622, dtype: object

In [156]:
k=pd.Series(data=[1,2])

In [157]:
type(k)

pandas.core.series.Series

In [158]:
k.astype("float")

0    1.0
1    2.0
dtype: float64

In [160]:
order_details["item_price"].str.replace("$","").astype("float")

0        2.39
1        3.39
2        3.39
3        2.39
4       16.98
        ...
4617    11.75
4618    11.75
4619    11.25
4620     8.75
4621     8.75
Name: item_price, Length: 4622, dtype: float64

### Steps to perform a data analysis

1. Bussiness understanding
2. Data collection
3. Data understanding
4. Data preparatio

### Chapter 4 Filtering, selection and sorting

In [161]:
import pandas as pd

In [27]:
euro_teams=pd.read_csv("Euro_2012_stats_Team.csv.csv")

In [167]:
euro_teams

,Team,Goals,Shots on target,Shots off target,Shooting Accuracy,% Goals-to-shots,Total shots (inc. Blocked),Hit Woodwork,Penalty goals,Penalties not scored,...,Saves made,Saves-to-shots ratio,Fouls Won,Fouls Conceded,Offsides,Yellow Cards,Red Cards,Subs on,Subs off,Players Used
0,Croatia,4,13,12,51.9%,16.0%,32,0,0,0,...,13,81.3%,41,62,2,9,0,9,9,16
1,Czech Republic,4,13,18,41.9%,12.9%,39,0,0,0,...,9,60.1%,53,73,8,7,0,11,11,19
2,Denmark,4,10,10,50.0%,20.0%,27,1,0,0,...,10,66.7%,25,38,8,4,0,7,7,15
3,England,5,11,18,50.0%,17.2%,40,0,0,0,...,22,88.1%,43,45,6,5,0,11,11,16
4,France,3,22,24,37.9%,6.5%,65,1,0,0,...,6,54.6%,36,51,5,6,0,11,11,19
5,Germany,10,32,32,47.8%,15.6%,80,2,1,0,...,10,62.6%,63,49,12,4,0,15,15,17
6,Greece,5,8,18,30.7%,19.2%,32,1,1,1,...,13,65.1%,67,48,12,9,1,12,12,20
7,Italy,6,34,45,43.0%,7.5%,110,2,0,0,...,20,74.1%,101,89,16,16,0,18,18,19
8,Netherlands,2,12,36,25.0%,4.1%,60,2,0,0,...,12,70.6%,35,30,3,5,0,7,7,15
9,Poland,2,15,23,39.4%,5.2%,48,0,0,0,...,6,66.7%,48,56,3,7,1,7,7,17
10,Portugal,6,22,42,34.3%,9.3%,82,6,0,0,...,10,71.5%,73,90,10,12,0,14,14,16
11,Republic of Ireland,1,7,12,36.8%,5.2%,28,0,0,0,...,17,65.4%,43,51,11,6,1,10,10,17
12,Russia,5,9,31,22.5%,12.5%,59,2,0,0,...,10,77.0%,34,43,4,6,0,7,7,16
13,Spain,12,42,33,55.9%,16.0%,100,0,1,0,...,15,93.8%,102,83,19,11,0,17,17,18
14,Sweden,5,17,19,47.2%,13.8%,39,3,0,0,...,8,61.6%,35,51,7,7,0,9,9,18
15,Ukraine,2,7,26,21.2%,6.0%,38,0,0,0,...,13,76.5%,48,31,4,5,0,9,9,18

### What is more important in the above euro table?

1. Find how one observation is linked to other observation thats very important to identify
2. Based on the data provided you have to ask questions automatically

### Did it display all 35 columns and what to do to get idea of al the column?

In [ ]:
No it displays only 10 columns at the start and 10 columns at the end due to the size constraint. If needed you can use other fuction to find what all other columns

In [171]:
euro_teams.columns

Index(['Team', 'Goals', 'Shots on target', 'Shots off target',
       'Shooting Accuracy', '% Goals-to-shots', 'Total shots (inc. Blocked)',
       'Hit Woodwork', 'Penalty goals', 'Penalties not scored', 'Headed goals',
       'Passes', 'Passes completed', 'Passing Accuracy', 'Touches', 'Crosses',
       'Dribbles', 'Corners Taken', 'Tackles', 'Clearances', 'Interceptions',
       'Clearances off line', 'Clean Sheets', 'Blocks', 'Goals conceded',
       'Saves made', 'Saves-to-shots ratio', 'Fouls Won', 'Fouls Conceded',
       'Offsides', 'Yellow Cards', 'Red Cards', 'Subs on', 'Subs off',
       'Players Used'],
      dtype='object')

In [ ]:
#pd.set_option("display.max_columns",None)  ----- dont use this coz it configure notebook to always display max columns which takes time to load

In [174]:
pd.set_option("display.max_columns",None)

In [175]:
euro_teams

,Team,Goals,Shots on target,Shots off target,Shooting Accuracy,% Goals-to-shots,Total shots (inc. Blocked),Hit Woodwork,Penalty goals,Penalties not scored,Headed goals,Passes,Passes completed,Passing Accuracy,Touches,Crosses,Dribbles,Corners Taken,Tackles,Clearances,Interceptions,Clearances off line,Clean Sheets,Blocks,Goals conceded,Saves made,Saves-to-shots ratio,Fouls Won,Fouls Conceded,Offsides,Yellow Cards,Red Cards,Subs on,Subs off,Players Used
0,Croatia,4,13,12,51.9%,16.0%,32,0,0,0,2,1076,828,76.9%,1706,60,42,14,49,83,56,NaN,0,10,3,13,81.3%,41,62,2,9,0,9,9,16
1,Czech Republic,4,13,18,41.9%,12.9%,39,0,0,0,0,1565,1223,78.1%,2358,46,68,21,62,98,37,2.0,1,10,6,9,60.1%,53,73,8,7,0,11,11,19
2,Denmark,4,10,10,50.0%,20.0%,27,1,0,0,3,1298,1082,83.3%,1873,43,32,16,40,61,59,0.0,1,10,5,10,66.7%,25,38,8,4,0,7,7,15
3,England,5,11,18,50.0%,17.2%,40,0,0,0,3,1488,1200,80.6%,2440,58,60,16,86,106,72,1.0,2,29,3,22,88.1%,43,45,6,5,0,11,11,16
4,France,3,22,24,37.9%,6.5%,65,1,0,0,0,2066,1803,87.2%,2909,55,76,28,71,76,58,0.0,1,7,5,6,54.6%,36,51,5,6,0,11,11,19
5,Germany,10,32,32,47.8%,15.6%,80,2,1,0,2,2774,2427,87.4%,3761,101,60,35,91,73,69,0.0,1,11,6,10,62.6%,63,49,12,4,0,15,15,17
6,Greece,5,8,18,30.7%,19.2%,32,1,1,1,0,1187,911,76.7%,2016,52,53,10,65,123,87,0.0,1,23,7,13,65.1%,67,48,12,9,1,12,12,20
7,Italy,6,34,45,43.0%,7.5%,110,2,0,0,2,3016,2531,83.9%,4363,75,75,30,98,137,136,1.0,2,18,7,20,74.1%,101,89,16,16,0,18,18,19
8,Netherlands,2,12,36,25.0%,4.1%,60,2,0,0,0,1556,1381,88.7%,2163,50,49,22,34,41,41,0.0,0,9,5,12,70.6%,35,30,3,5,0,7,7,15
9,Poland,2,15,23,39.4%,5.2%,48,0,0,0,1,1059,852,80.4%,1724,55,39,14,67,87,62,0.0,0,8,3,6,66.7%,48,56,3,7,1,7,7,17
10,Portugal,6,22,42,34.3%,9.3%,82,6,0,0,2,1891,1461,77.2%,2958,91,64,41,78,92,86,0.0,2,11,4,10,71.5%,73,90,10,12,0,14,14,16
11,Republic of Ireland,1,7,12,36.8%,5.2%,28,0,0,0,1,851,606,71.2%,1433,43,18,8,45,78,43,1.0,0,23,9,17,65.4%,43,51,11,6,1,10,10,17
12,Russia,5,9,31,22.5%,12.5%,59,2,0,0,1,1602,1345,83.9%,2278,40,40,21,65,74,58,0.0,0,8,3,10,77.0%,34,43,4,6,0,7,7,16
13,Spain,12,42,33,55.9%,16.0%,100,0,1,0,2,4317,3820,88.4%,5585,69,106,44,122,102,79,0.0,5,8,1,15,93.8%,102,83,19,11,0,17,17,18
14,Sweden,5,17,19,47.2%,13.8%,39,3,0,0,1,1192,965,80.9%,1806,44,29,7,56,54,45,0.0,1,12,5,8,61.6%,35,51,7,7,0,9,9,18
15,Ukraine,2,7,26,21.2%,6.0%,38,0,0,0,2,1276,1043,81.7%,1894,33,26,18,65,97,29,0.0,0,4,4,13,76.5%,48,31,4,5,0,9,9,18

### How to fileter three columns goals, red card and yellow card from dataset?

In [191]:
euro_teams["Team"] #filters one column which gives you a series

0                 Croatia
1          Czech Republic
2                 Denmark
3                 England
4                  France
5                 Germany
6                  Greece
7                   Italy
8             Netherlands
9                  Poland
10               Portugal
11    Republic of Ireland
12                 Russia
13                  Spain
14                 Sweden
15                Ukraine
Name: Team, dtype: object

In [194]:
euro_teams[["Team","Goals","Yellow Cards","Red Cards"]] #Filters more than one columns as a data frame

                   Team  Goals  Yellow Cards  Red Cards
0               Croatia      4             9          0
1        Czech Republic      4             7          0
2               Denmark      4             4          0
3               England      5             5          0
4                France      3             6          0
5               Germany     10             4          0
6                Greece      5             9          1
7                 Italy      6            16          0
8           Netherlands      2             5          0
9                Poland      2             7          1
10             Portugal      6            12          0
11  Republic of Ireland      1             6          1
12               Russia      5             6          0
13                Spain     12            11          0
14               Sweden      5             7          0
15              Ukraine      2             5          0

### Can you give descriptive statistics for the above?
euro_teams[["Team","Goals","Yellow Cards","Red Cards"]]

In [199]:
euro_teams[["Team","Goals","Yellow Cards","Red Cards"]].describe(include="all")

           Team      Goals  Yellow Cards  Red Cards
count        16  16.000000     16.000000  16.000000
unique       16        NaN           NaN        NaN
top     Croatia        NaN           NaN        NaN
freq          1        NaN           NaN        NaN
mean        NaN   4.750000      7.437500   0.187500
std         NaN   2.886751      3.265348   0.403113
min         NaN   1.000000      4.000000   0.000000
25%         NaN   2.750000      5.000000   0.000000
50%         NaN   4.500000      6.500000   0.000000
75%         NaN   5.250000      9.000000   0.000000
max         NaN  12.000000     16.000000   1.000000

### Which team have maximum yellow and red card overall?

In [211]:
euro_teams[["Team","Goals","Yellow Cards","Red Cards"]].sort_values(ascending=False, by=["Yellow Cards","Red Cards"])

                   Team  Goals  Yellow Cards  Red Cards
7                 Italy      6            16          0
10             Portugal      6            12          0
13                Spain     12            11          0
6                Greece      5             9          1
0               Croatia      4             9          0
9                Poland      2             7          1
1        Czech Republic      4             7          0
14               Sweden      5             7          0
11  Republic of Ireland      1             6          1
4                France      3             6          0
12               Russia      5             6          0
3               England      5             5          0
8           Netherlands      2             5          0
15              Ukraine      2             5          0
2               Denmark      4             4          0
5               Germany     10             4          0

### Which team have got red cards give me only those team?

In [212]:
filtered_euro=euro_teams[["Team","Goals","Yellow Cards","Red Cards"]]

In [213]:
filtered_euro

                   Team  Goals  Yellow Cards  Red Cards
0               Croatia      4             9          0
1        Czech Republic      4             7          0
2               Denmark      4             4          0
3               England      5             5          0
4                France      3             6          0
5               Germany     10             4          0
6                Greece      5             9          1
7                 Italy      6            16          0
8           Netherlands      2             5          0
9                Poland      2             7          1
10             Portugal      6            12          0
11  Republic of Ireland      1             6          1
12               Russia      5             6          0
13                Spain     12            11          0
14               Sweden      5             7          0
15              Ukraine      2             5          0

In [218]:
filtered_euro["Red Cards"]>0 #prints only the series not the team name and other columns

0     False
1     False
2     False
3     False
4     False
5     False
6      True
7     False
8     False
9      True
10    False
11     True
12    False
13    False
14    False
15    False
Name: Red Cards, dtype: bool

In [217]:
filtered_euro[filtered_euro["Red Cards"]>0]   #prints the whole dataframe not the team name and other columns

                   Team  Goals  Yellow Cards  Red Cards
6                Greece      5             9          1
9                Poland      2             7          1
11  Republic of Ireland      1             6          1

### List the team which got more than 8 yellow cards?

In [224]:
filtered_euro[filtered_euro["Yellow Cards"]>=8].sort_values(by="Yellow Cards",ascending=False)

        Team  Goals  Yellow Cards  Red Cards
7      Italy      6            16          0
10  Portugal      6            12          0
13     Spain     12            11          0
0    Croatia      4             9          0
6     Greece      5             9          1

### Chapter 5 : How to deal with missing values

In [65]:
it_employee=pd.read_csv("Employee_data.csv.csv") # compare one observation to other observations to understand the data

In [66]:
it_employee

      Name   Age Department   Salary   Join_Date
0   Rajesh  29.0        Ops  60000.0  21-05-2023
1    Nasir  31.0    IT Tech      NaN  12-11-2020
2  Mathiew   NaN    Support  58000.0  15-01-2025
3  Gilbert  29.0        Ops  60000.0  21-05-2021
4    Kevin  28.0    Support  61000.0  30-07-2024
5    Navin  35.0    Support  72000.0  19-08-2023
6      NaN  40.0         IT  64000.0  10-09-2022
7    Nasir  31.0    IT Tech      NaN  12-11-2020

### What are the steps to be performed before dealing with the missing value?

Always call the client and ask why there is missing value in the data and ask do they have other file or ask do theyu want us to perform data cleaning

Step 1. Data cleaning

### Step 1. Data cleaning (Level 1)

### Remove the duplicate values

In [67]:
it_employee=it_employee.drop_duplicates()

In [234]:
it_employee

      Name   Age Department   Salary   Join_Date
0   Rajesh  29.0        Ops  60000.0  21-05-2023
1    Nasir  31.0    IT Tech      NaN  12-11-2020
2  Mathiew   NaN    Support  58000.0  15-01-2025
3  Gilbert  29.0        Ops  60000.0  21-05-2021
4    Kevin  28.0    Support  61000.0  30-07-2024
5    Navin  35.0    Support  72000.0  19-08-2023
6      NaN  40.0         IT  64000.0  10-09-2022

### is there any other alternative to replace the orginal data as per the below code?
it_employee=it_employee.drop_duplicates()

In [68]:
it_employee.drop_duplicates(inplace=True) # we can use a argument called as inplace = True in some functions which changes the data in orginal data

C:\Users\Q848957\AppData\Local\Temp\ipykernel_6152\2725920509.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  it_employee.drop_duplicates(inplace=True) # we can use a argument called as inplace = True in some functions which changes the data in orginal data

In [239]:
it_employee

      Name   Age Department   Salary   Join_Date
0   Rajesh  29.0        Ops  60000.0  21-05-2023
1    Nasir  31.0    IT Tech      NaN  12-11-2020
2  Mathiew   NaN    Support  58000.0  15-01-2025
3  Gilbert  29.0        Ops  60000.0  21-05-2021
4    Kevin  28.0    Support  61000.0  30-07-2024
5    Navin  35.0    Support  72000.0  19-08-2023
6      NaN  40.0         IT  64000.0  10-09-2022

### Step 2: Find out the null entries in each column (you have forgot the code)

In [69]:
it_employee.isnull().sum()

Name          1
Age           1
Department    0
Salary        1
Join_Date     0
dtype: int64

### If there is null values for one column? should we add our own data?

1. No we should not add wrong add data as it causes issue for building prediction model
2. If client approves its always safe to remove the data instead of entering wrong data
3. if a name itself not there for a employee safest bet is to remove that data
4. Before you start analysis of client data you need to know the shape of that dataset
5. After removing or perfoorming datanalysis youneed to show the shape of the current one

In [254]:
it_employee.shape

(7, 5)

### How to remove all the null valued rows?

In [70]:
it_employee.dropna() #remove all the null entried rows

      Name   Age Department   Salary   Join_Date
0   Rajesh  29.0        Ops  60000.0  21-05-2023
3  Gilbert  29.0        Ops  60000.0  21-05-2021
4    Kevin  28.0    Support  61000.0  30-07-2024
5    Navin  35.0    Support  72000.0  19-08-2023

In [71]:
it_employee.dropna(inplace=True) #completly changes the orginal data by removing the null records

C:\Users\Q848957\AppData\Local\Temp\ipykernel_6152\1323475800.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  it_employee.dropna(inplace=True) #completly changes the orginal data by removing the null records

In [258]:
it_employee.shape

(4, 5)

### Step 3: Record in a Document

. Client gave totally 7 Obseravations out of which 3 entries are removed because those records do not have complete information.

### Step 4: Get Approval
. Send this to Client and get the approval to proceed for Model Building or Model Training

### Level 2 : Data cleaning

### Can you open another csv subsheet from CSV workbook using read_csv()

In [ ]:
#read_csv() doesnt have seperate function to intake multiple sheets in the same workbook. read_excel() have the function

In [ ]:
#need to save the same csv sheet as excel workbook so that you can access all the subsheets or sheets

In [72]:
pd.read_csv()

TypeError: read_csv() missing 1 required positional argument: 'filepath_or_buffer'

In [2]:
import pandas as pd
pd.read_excel("Employee_data.csv.xlsx")

ImportError: Missing optional dependency 'openpyxl'.  Use pip or conda to install openpyxl.

In [3]:
pip install openpyxl

Collecting openpyxl
  Downloading openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
     ---------------------------------------- 0.0/250.9 kB ? eta -:--:--
     ----------- --------------------------- 71.7/250.9 kB 1.3 MB/s eta 0:00:01
     ------------------------------- ------ 204.8/250.9 kB 2.1 MB/s eta 0:00:01
     -------------------------------------- 250.9/250.9 kB 2.2 MB/s eta 0:00:00
Collecting et-xmlfile
  Downloading et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: et-xmlfile, openpyxl
Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 23.0.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [145]:
import pandas as pd
employee_details=pd.read_excel("Employee_data.csv.xlsx",sheet_name="Second")

In [13]:
employee_details.dtypes

Name           object
Age           float64
Department     object
Salary        float64
Join_Date      object
dtype: object

In [16]:
employee_details.describe(include="all")

           Name        Age Department        Salary   Join_Date
count        14  13.000000         15      9.000000          14
unique       13        NaN          3           NaN           8
top     Mathiew        NaN    IT Tech           NaN  21-05-2021
freq          2        NaN          6           NaN           4
mean        NaN  30.307692        NaN  62000.000000         NaN
std         NaN   3.568020        NaN   4272.001873         NaN
min         NaN  28.000000        NaN  58000.000000         NaN
25%         NaN  28.000000        NaN  60000.000000         NaN
50%         NaN  29.000000        NaN  61000.000000         NaN
75%         NaN  31.000000        NaN  63000.000000         NaN
max         NaN  40.000000        NaN  72000.000000         NaN

In [23]:
employee_details.isnull().sum()

Name          1
Age           2
Department    0
Salary        6
Join_Date     1
dtype: int64

### How to find how many duplicate columns are there?

In [25]:
employee_details[employee_details.duplicated()]

       Name  Age Department   Salary   Join_Date
11  Mathiew  NaN    Support  58000.0  15-01-2025

### Drop duplicates

In [146]:
employee_details.drop_duplicates(inplace=True)

In [20]:
employee_details

            Name   Age Department   Salary   Join_Date
0         Rajesh  29.0        Ops  60000.0  21-05-2023
1          Nasir  31.0    IT Tech  62000.0  21-11-2020
2        Mathiew   NaN    Support  58000.0  15-01-2025
3        Gilbert  29.0        Ops  60000.0  21-05-2021
4          Kevin  28.0    Support  61000.0  30-07-2024
5          Navin  35.0    Support  72000.0  19-08-2023
6            NaN  40.0    IT Tech  64000.0  09-10-2022
7         Roshan  31.0    IT Tech      NaN  12-11-2020
8     Kuppuswamy  28.0        Ops      NaN  21-05-2021
9          Ajesh  28.0    Support      NaN  30-07-2024
10         Divya  31.0    IT Tech  63000.0  12-11-2020
12  Jagadeshwari  28.0    IT Tech      NaN         NaN
13          Mani  28.0        Ops      NaN  21-05-2021
14         Karim  28.0    IT Tech      NaN  21-05-2021

### Identufy null entries in the todal dataset?

In [28]:
employee_details.isna().sum()

Name          1
Age           2
Department    0
Salary        6
Join_Date     1
dtype: int64

### Step 3 of level 2 - Go to imputation? How to find the pattern in non-missing values so that a value can be imputed to missing value

In [31]:
employee_details[employee_details["Department"]=="IT Tech"]

            Name   Age Department   Salary   Join_Date
1          Nasir  31.0    IT Tech  62000.0  21-11-2020
6            NaN  40.0    IT Tech  64000.0  09-10-2022
7         Roshan  31.0    IT Tech      NaN  12-11-2020
10         Divya  31.0    IT Tech  63000.0  12-11-2020
12  Jagadeshwari  28.0    IT Tech      NaN         NaN
14         Karim  28.0    IT Tech      NaN  21-05-2021

In [32]:
# The salary seems to be related to the age so please find is the same pattern follwed for other department as well
#Pattern here is 31 aged people getting 62k to 63k and 40 age getting 64k so the 28 aged people should be getting less salary based on their year of experience

In [33]:
employee_details[employee_details["Department"]=="Ops"]

          Name   Age Department   Salary   Join_Date
0       Rajesh  29.0        Ops  60000.0  21-05-2023
3      Gilbert  29.0        Ops  60000.0  21-05-2021
8   Kuppuswamy  28.0        Ops      NaN  21-05-2021
13        Mani  28.0        Ops      NaN  21-05-2021

In [ ]:
#please try to find the pattern based on the comparision

In [34]:
employee_details[employee_details["Department"]=="Support"]

       Name   Age Department   Salary   Join_Date
2   Mathiew   NaN    Support  58000.0  15-01-2025
4     Kevin  28.0    Support  61000.0  30-07-2024
5     Navin  35.0    Support  72000.0  19-08-2023
9     Ajesh  28.0    Support      NaN  30-07-2024
11  Mathiew   NaN    Support  58000.0  15-01-2025

### How to add two condition for filtering the null values in support team? can it be written in a single statement?

In [35]:
employee_details[employee_details["Department"]=="Support"0 & employee_details["Department"].isna()] #missed brackets and  second condition is wrong

TypeError: Cannot perform 'rand_' with a dtyped [bool] array and scalar of type [bool]

In [38]:
employee_details[(employee_details["Department"]=="Support") & (employee_details["Salary"].isna())]

    Name   Age Department  Salary   Join_Date
9  Ajesh  28.0    Support     NaN  30-07-2024

### Data Analytics Task

1. Impute The relevant values in the Salary Column wherever it is NaN, based on Department Filtering.
2. Find and Impute relevant age for Mathiew

In [42]:
employee_details

            Name   Age Department   Salary   Join_Date
0         Rajesh  29.0        Ops  60000.0  21-05-2023
1          Nasir  31.0    IT Tech  62000.0  21-11-2020
2        Mathiew   NaN    Support  58000.0  15-01-2025
3        Gilbert  29.0        Ops  60000.0  21-05-2021
4          Kevin  28.0    Support  61000.0  30-07-2024
5          Navin  35.0    Support  72000.0  19-08-2023
6            NaN  40.0    IT Tech  64000.0  09-10-2022
7         Roshan  31.0    IT Tech      NaN  12-11-2020
8     Kuppuswamy  28.0        Ops      NaN  21-05-2021
9          Ajesh  28.0    Support      NaN  30-07-2024
10         Divya  31.0    IT Tech  63000.0  12-11-2020
11       Mathiew   NaN    Support  58000.0  15-01-2025
12  Jagadeshwari  28.0    IT Tech      NaN         NaN
13          Mani  28.0        Ops      NaN  21-05-2021
14         Karim  28.0    IT Tech      NaN  21-05-2021

In [121]:
employee_details.drop_duplicates(inplace=True)

In [44]:
employee_details

            Name   Age Department   Salary   Join_Date
0         Rajesh  29.0        Ops  60000.0  21-05-2023
1          Nasir  31.0    IT Tech  62000.0  21-11-2020
2        Mathiew   NaN    Support  58000.0  15-01-2025
3        Gilbert  29.0        Ops  60000.0  21-05-2021
4          Kevin  28.0    Support  61000.0  30-07-2024
5          Navin  35.0    Support  72000.0  19-08-2023
6            NaN  40.0    IT Tech  64000.0  09-10-2022
7         Roshan  31.0    IT Tech      NaN  12-11-2020
8     Kuppuswamy  28.0        Ops      NaN  21-05-2021
9          Ajesh  28.0    Support      NaN  30-07-2024
10         Divya  31.0    IT Tech  63000.0  12-11-2020
12  Jagadeshwari  28.0    IT Tech      NaN         NaN
13          Mani  28.0        Ops      NaN  21-05-2021
14         Karim  28.0    IT Tech      NaN  21-05-2021

### Sorting salary and age to find the relation?

28 -61000
29-60000
29-60000
31-62/63
35-72
40-64k
Based on this i am understanding that for all 28 age i can add 60 or 61k and 31 63k 
may be i can find average of this salary and add

In [122]:
employee_details[["Age","Salary"]].sort_values(by=["Age","Salary"])

     Age   Salary
4   28.0  61000.0
8   28.0      NaN
9   28.0      NaN
12  28.0      NaN
13  28.0      NaN
14  28.0      NaN
0   29.0  60000.0
3   29.0  60000.0
1   31.0  62000.0
10  31.0  63000.0
7   31.0      NaN
5   35.0  72000.0
6   40.0  64000.0
2    NaN  58000.0

In [123]:
employee_details.groupby("Age")["Salary"].mean().to_frame()

       Salary
Age
28.0  61000.0
29.0  60000.0
31.0  62500.0
35.0  72000.0
40.0  64000.0

In [ ]:
#Assigning 60k mean value for 28 aged and Nan value records

In [147]:
employee_details.loc[(employee_details["Age"] == 28) & (employee_details["Salary"].isna()), "Salary"] = 60000.0

In [ ]:
#Assigning 62500 mean value for 31 aged and Nan value records

In [148]:
employee_details.loc[(employee_details["Age"] == 31) & (employee_details["Salary"].isna()), "Salary"] = 62500.0

### Finding and imputing relevant age for Mathew

In [140]:
employee_details[["Age","Salary"]].sort_values(by=["Age","Salary"])

     Age   Salary
8   28.0  60000.0
9   28.0  60000.0
12  28.0  60000.0
13  28.0  60000.0
14  28.0  60000.0
4   28.0  61000.0
0   29.0  60000.0
3   29.0  60000.0
1   31.0  62000.0
7   31.0  62500.0
10  31.0  63000.0
5   35.0  72000.0
6   40.0  64000.0
2    NaN  58000.0

In [141]:
employee_details.groupby("Salary")["Age"].mean()

Salary
58000.0          NaN
60000.0    28.285714
61000.0    28.000000
62000.0    31.000000
62500.0    31.000000
63000.0    31.000000
64000.0    40.000000
72000.0    35.000000
Name: Age, dtype: float64

In [158]:
employee_details[employee_details["Name"] == "Mathiew"]["Age"]=27

C:\Users\Q848957\AppData\Local\Temp\ipykernel_28804\400574168.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  employee_details[employee_details["Name"] == "Mathiew"]["Age"]=27

In [164]:
employee_details.loc[(employee_details["Name"] == "Mathiew"),("Age")]=27

In [165]:
employee_details

            Name   Age Department   Salary   Join_Date
0         Rajesh  29.0        Ops  60000.0  21-05-2023
1          Nasir  31.0    IT Tech  62000.0  21-11-2020
2        Mathiew  27.0    Support  58000.0  15-01-2025
3        Gilbert  29.0        Ops  60000.0  21-05-2021
4          Kevin  28.0    Support  61000.0  30-07-2024
5          Navin  35.0    Support  72000.0  19-08-2023
6            NaN  40.0    IT Tech  64000.0  09-10-2022
7         Roshan  31.0    IT Tech  62500.0  12-11-2020
8     Kuppuswamy  28.0        Ops  60000.0  21-05-2021
9          Ajesh  28.0    Support  60000.0  30-07-2024
10         Divya  31.0    IT Tech  63000.0  12-11-2020
12  Jagadeshwari  28.0    IT Tech  60000.0         NaN
13          Mani  28.0        Ops  60000.0  21-05-2021
14         Karim  28.0    IT Tech  60000.0  21-05-2021