### 1.	Write a program to take a name and age from the user and print a greeting message

In [1]:
def user_details():
    user_name=input("Enter your name please")
    user_age=input("Enter yourage please")
    print("Hey {} {} years old, welcome to our team".format(user_name,user_age))

In [2]:
user_details()

Enter your name please Ravi
Enter yourage please 28

Hey Ravi 28 years old, welcome to our team

### 2.	Create a list of numbers and print only even numbers using a for loop

In [4]:
def even_numbers(start=1,stop=50):
    print("Your list of even numbers are")
    for i in range (start,stop):
        if i%2==0:
            print(i)

In [6]:
even_numbers(2,20)

Your list of even numbers are
2
4
6
8
10
12
14
16
18

### 3.	Write a program that handles division by zero using try-except?

In [16]:
def division(numerator=1,denominator=0):
    try:
        Answer=numerator/denominator
        print (Answer)
    except ZeroDivisionError:
        print("sorry 0 is not accepted as denominator, please input correct denominator")

In [19]:
division()

sorry 0 is not accepted as denominator, please input correct denominator

### 4.	Given a string, count how many vowels it has

In [39]:
def vowels():
    user_string=input("Enter the word to check how many vowels")
    vowels=["a","e","i","o","u"]
    vowel_count=0
    vowel_present=[]
    for string in user_string:
        for letters in vowels:
            if string==letters:
                vowel_count=vowel_count+1
                vowel_present.append(string)
    print(f"You have total {vowel_count} and those vowels are {vowel_present}")

In [40]:
vowels()

Enter the word to check how many vowels Pirates of carribean

You have total 8 and those vowels are ['i', 'a', 'e', 'o', 'a', 'i', 'e', 'a']

### 5.	Reverse a list without using built-in functions

In [87]:
def reverse():
    user_string=input("Enter the word to reverse")
    reverse=[]
    for string in range(0,len(user_string)):
        reverse.append(user_string[-string-1])
    reverse="".join(reverse)
    print("Your reverse word is {}".format(reverse))

In [74]:
reverse()

Enter the word to reverse king

Your reverse word is gnik

### 6.	Create a dictionary with at least 5 key-value pairs and print them

In [91]:
Sample={"Kumar":{"Score":[30,40,50,60]},
         "Ram":{"Score":[100,90,70,50]},
        "Riyash":{"Score":[60,30,60,50]},
        "Priya":{"Score":[60,30,40,50]}}

In [96]:
print(Sample)

{'Kumar': {'Score': [30, 40, 50, 60]}, 'Ram': {'Score': [100, 90, 70, 50]}, 'Riyash': {'Score': [60, 30, 60, 50]}, 'Priya': {'Score': [60, 30, 40, 50]}}

### 7.	Write a Pandas code to read a CSV and print the top 5 rows.

In [99]:
import pandas as pd
pd.read_csv("Employee_sample.csv")

,Name,Joining Date,Email Address,Department,Monthly Salary,Job Status
0,Mark,31-Dec-21,Mark@demomail.com,Human Resources,"$5,830",Permanent
1,Brian,31-Dec-21,Brian@demomail.com,Sales,"$3,450",Permanent
2,Alan,14-Jan-22,Alan@demomail.com,Legal,"$4,920",Permanent
3,Tony,14-Jan-22,Tony@demomail.com,Retail,"$2,785",Permanent
4,Agatha,1-Feb-22,Agatha@demomail.com,Sales,"$3,450",Permanent
5,Lana,1-Feb-22,Lana@demomail.com,Accounting,"$3,125",Permanent
6,Heather,4-Aug-22,Heather@demomail.com,Accounting,"$3,125",NaN
7,Ben,4-Aug-22,Ben@demomail.com,Sales,"$3,450",NaN
8,Caitlyn,1-Mar-22,Caitlyn@demomail.com,Retail,"$2,785",Permanent
9,Gibbs,1-Mar-22,Gibbs@demomail.com,Retail,"$2,785",Permanent
10,Anderson,1-Mar-22,Anderson@demomail.com,Sales,"$3,450",Permanent
11,Michael,1-Mar-22,Michael@demomail.com,Retail,"$2,785",Permanent
12,David,15-Mar-22,David@demomail.com,Sales,"$3,450",NaN
13,Jacob,15-Mar-22,Jacob@demomail.com,Support,"$2,500",NaN
14,John,1-Apr-22,John@demomail.com,Business Development,"$3,100",NaN
15,Leonardo,1-Apr-22,Leonardo@demomail.com,Business Development,"$3,100",NaN
16,Matthew,17-Apr-22,Matthew@demomail.com,Human Resources,"$5,830",NaN
17,Joana,1-Jun-22,Joana@demomail.com,Business Development,"$3,100",NaN
18,Ross,2-Jul-22,Ross@demomail.com,Legal,"$4,920",NaN
19,Joey,15-Jul-22,Joey@demomail.com,Business Development,"$3,100",NaN
20,Jack,3-Jan-22,Jack@demomail.com,Support,"$2,500",Permanent

### 8.	Create a DataFrame from a Python dictionary?

In [100]:
Sample={"Kumar":{"Score":[30,40,50,60]},
         "Ram":{"Score":[100,90,70,50]},
        "Riyash":{"Score":[60,30,60,50]},
        "Priya":{"Score":[60,30,40,50]}}

In [101]:
import pandas as pd
pd.DataFrame(Sample)

                  Kumar                Ram            Riyash             Priya
Score  [30, 40, 50, 60]  [100, 90, 70, 50]  [60, 30, 60, 50]  [60, 30, 40, 50]

### 9.	Replace all missing values in a DataFrame with the column’s mean.

In [177]:
import pandas as pd
Employee_salary=pd.read_csv("Employee_sample.csv")
Employee_salary

,Name,Joining Date,Email Address,Department,Monthly Salary,Job Status,Age
0,Mark,31-Dec-21,Mark@demomail.com,Human Resources,"$5,830",Permanent,25.0
1,Brian,31-Dec-21,Brian@demomail.com,Sales,NaN,Permanent,35.0
2,Alan,14-Jan-22,Alan@demomail.com,Legal,"$4,920",Permanent,43.0
3,Tony,14-Jan-22,Tony@demomail.com,Retail,"$2,785",Permanent,31.0
4,Agatha,1-Feb-22,Agatha@demomail.com,Sales,NaN,Permanent,NaN
5,Lana,1-Feb-22,Lana@demomail.com,Accounting,"$3,125",Permanent,NaN
6,Heather,4-Aug-22,Heather@demomail.com,Accounting,"$3,125",NaN,21.0
7,Ben,4-Aug-22,Ben@demomail.com,Sales,"$3,450",NaN,23.0
8,Caitlyn,1-Mar-22,Caitlyn@demomail.com,Retail,"$2,785",Permanent,34.0
9,Gibbs,1-Mar-22,Gibbs@demomail.com,Retail,NaN,Permanent,36.0
10,Anderson,1-Mar-22,Anderson@demomail.com,Sales,"$3,450",Permanent,NaN
11,Michael,1-Mar-22,Michael@demomail.com,Retail,"$2,785",Permanent,50.0
12,David,15-Mar-22,David@demomail.com,Sales,"$3,450",NaN,42.0
13,Jacob,15-Mar-22,Jacob@demomail.com,Support,"$2,500",NaN,NaN
14,John,1-Apr-22,John@demomail.com,Business Development,"$3,100",NaN,30.0
15,Leonardo,1-Apr-22,Leonardo@demomail.com,Business Development,"$3,100",NaN,40.0
16,Matthew,17-Apr-22,Matthew@demomail.com,Human Resources,NaN,NaN,NaN
17,Joana,1-Jun-22,Joana@demomail.com,Business Development,"$3,100",NaN,42.0
18,Ross,2-Jul-22,Ross@demomail.com,Legal,NaN,NaN,NaN
19,Joey,15-Jul-22,Joey@demomail.com,Business Development,"$3,100",NaN,41.0
20,Jack,3-Jan-22,Jack@demomail.com,Support,"$2,500",Permanent,25.0

In [ ]:
#replacing the string $ and , characters with empty character

In [178]:
Employee_salary["Monthly Salary"]=Employee_salary["Monthly Salary"].str.replace(r"[$,]","",regex=True).str.strip().astype("float")

In [ ]:
 #mean of salary

In [212]:
Employee_salary["Monthly Salary"].mean()

np.float64(3319.0625)

In [ ]:
 # Missing salary replaced with mean of salary

In [219]:
Employee_salary["Monthly Salary"].replace(float("nan"),Employee_salary["Monthly Salary"].mean(),inplace=True) #mean of salary was replaced in

In [ ]:
 # Missing age values replaced with mean age

In [220]:
Employee_salary["Age"].replace(float("nan"),Employee_salary["Age"].mean(),inplace=True)

C:\Users\Q848957\AppData\Local\Temp\ipykernel_26760\953721310.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  Employee_salary["Age"].replace(float("nan"),Employee_salary["Age"].mean(),inplace=True)

In [221]:
Employee_salary

,Name,Joining Date,Email Address,Department,Monthly Salary,Job Status,Age
0,Mark,31-Dec-21,Mark@demomail.com,Human Resources,5830.0000,Permanent,25.000000
1,Brian,31-Dec-21,Brian@demomail.com,Sales,3319.0625,Permanent,35.000000
2,Alan,14-Jan-22,Alan@demomail.com,Legal,4920.0000,Permanent,43.000000
3,Tony,14-Jan-22,Tony@demomail.com,Retail,2785.0000,Permanent,31.000000
4,Agatha,1-Feb-22,Agatha@demomail.com,Sales,3319.0625,Permanent,34.533333
5,Lana,1-Feb-22,Lana@demomail.com,Accounting,3125.0000,Permanent,34.533333
6,Heather,4-Aug-22,Heather@demomail.com,Accounting,3125.0000,NaN,21.000000
7,Ben,4-Aug-22,Ben@demomail.com,Sales,3450.0000,NaN,23.000000
8,Caitlyn,1-Mar-22,Caitlyn@demomail.com,Retail,2785.0000,Permanent,34.000000
9,Gibbs,1-Mar-22,Gibbs@demomail.com,Retail,3319.0625,Permanent,36.000000
10,Anderson,1-Mar-22,Anderson@demomail.com,Sales,3450.0000,Permanent,34.533333
11,Michael,1-Mar-22,Michael@demomail.com,Retail,2785.0000,Permanent,50.000000
12,David,15-Mar-22,David@demomail.com,Sales,3450.0000,NaN,42.000000
13,Jacob,15-Mar-22,Jacob@demomail.com,Support,2500.0000,NaN,34.533333
14,John,1-Apr-22,John@demomail.com,Business Development,3100.0000,NaN,30.000000
15,Leonardo,1-Apr-22,Leonardo@demomail.com,Business Development,3100.0000,NaN,40.000000
16,Matthew,17-Apr-22,Matthew@demomail.com,Human Resources,3319.0625,NaN,34.533333
17,Joana,1-Jun-22,Joana@demomail.com,Business Development,3100.0000,NaN,42.000000
18,Ross,2-Jul-22,Ross@demomail.com,Legal,3319.0625,NaN,34.533333
19,Joey,15-Jul-22,Joey@demomail.com,Business Development,3100.0000,NaN,41.000000
20,Jack,3-Jan-22,Jack@demomail.com,Support,2500.0000,Permanent,25.000000

### 10.	Filter rows in a DataFrame where the "Age" column is greater than 30.

In [223]:
Employee_salary[Employee_salary["Age"]>30]

,Name,Joining Date,Email Address,Department,Monthly Salary,Job Status,Age
1,Brian,31-Dec-21,Brian@demomail.com,Sales,3319.0625,Permanent,35.000000
2,Alan,14-Jan-22,Alan@demomail.com,Legal,4920.0000,Permanent,43.000000
3,Tony,14-Jan-22,Tony@demomail.com,Retail,2785.0000,Permanent,31.000000
4,Agatha,1-Feb-22,Agatha@demomail.com,Sales,3319.0625,Permanent,34.533333
5,Lana,1-Feb-22,Lana@demomail.com,Accounting,3125.0000,Permanent,34.533333
8,Caitlyn,1-Mar-22,Caitlyn@demomail.com,Retail,2785.0000,Permanent,34.000000
9,Gibbs,1-Mar-22,Gibbs@demomail.com,Retail,3319.0625,Permanent,36.000000
10,Anderson,1-Mar-22,Anderson@demomail.com,Sales,3450.0000,Permanent,34.533333
11,Michael,1-Mar-22,Michael@demomail.com,Retail,2785.0000,Permanent,50.000000
12,David,15-Mar-22,David@demomail.com,Sales,3450.0000,NaN,42.000000
13,Jacob,15-Mar-22,Jacob@demomail.com,Support,2500.0000,NaN,34.533333
15,Leonardo,1-Apr-22,Leonardo@demomail.com,Business Development,3100.0000,NaN,40.000000
16,Matthew,17-Apr-22,Matthew@demomail.com,Human Resources,3319.0625,NaN,34.533333
17,Joana,1-Jun-22,Joana@demomail.com,Business Development,3100.0000,NaN,42.000000
18,Ross,2-Jul-22,Ross@demomail.com,Legal,3319.0625,NaN,34.533333
19,Joey,15-Jul-22,Joey@demomail.com,Business Development,3100.0000,NaN,41.000000